# Generated by Django 4.0.4 on 2022-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=500, unique=True)),
                ('url_id', models.CharField(max_length=7)),
            ],
        ),
    ]
