# Generated by Django 4.0.4 on 2022-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='https://shorty/', max_length=40),
        ),
    ]
